<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gsmservice\Gateway\Models\Components;


/** AccountResponse - An object containing information about the User's account and balance */
class AccountResponse
{
    /**
     * User Login
     *
     * @var ?string $login
     */
    #[\JMS\Serializer\Annotation\SerializedName('login')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $login = null;

    /**
     * Account type
     *
     * @var ?AccountType $accountType
     */
    #[\JMS\Serializer\Annotation\SerializedName('account_type')]
    #[\JMS\Serializer\Annotation\Type('\Gsmservice\Gateway\Models\Components\AccountType|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?AccountType $accountType = null;

    /**
     * Acount limit
     *
     * @var ?float $limit
     */
    #[\JMS\Serializer\Annotation\SerializedName('limit')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $limit = null;

    /**
     * Current account balance
     *
     * @var ?float $credit
     */
    #[\JMS\Serializer\Annotation\SerializedName('credit')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $credit = null;

    /**
     * Subaccount credit balance (null if unlimited)
     *
     * @var ?float $subcredit
     */
    #[\JMS\Serializer\Annotation\SerializedName('subcredit')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $subcredit = null;

    /**
     * Account currency
     *
     * @var ?string $currency
     */
    #[\JMS\Serializer\Annotation\SerializedName('currency')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $currency = null;

    /**
     * User name and surname
     *
     * @var ?string $name
     */
    #[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * Is main account?
     *
     * @var ?bool $isMain
     */
    #[\JMS\Serializer\Annotation\SerializedName('is_main')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?bool $isMain = null;

    /**
     * @param  ?string  $login
     * @param  ?AccountType  $accountType
     * @param  ?float  $limit
     * @param  ?float  $credit
     * @param  ?string  $currency
     * @param  ?string  $name
     * @param  ?bool  $isMain
     * @param  ?float  $subcredit
     */
    public function __construct(?string $login = null, ?AccountType $accountType = null, ?float $limit = null, ?float $credit = null, ?string $currency = null, ?string $name = null, ?bool $isMain = null, ?float $subcredit = null)
    {
        $this->login = $login;
        $this->accountType = $accountType;
        $this->limit = $limit;
        $this->credit = $credit;
        $this->currency = $currency;
        $this->name = $name;
        $this->isMain = $isMain;
        $this->subcredit = $subcredit;
    }
}