<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gsmservice\Gateway\Models\Components;


/** Account type */
enum AccountType: string
{
    case PrePaid = 'PRE-PAID';
    case PostPaid = 'POST-PAID';
}
