<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gsmservice\Gateway\Models\Components;


/** CancelledMessage - An object containing information about results of cancelling single message */
class CancelledMessage
{
    /**
     * Message ID
     *
     * @var ?int $id
     */
    #[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $id = null;

    /**
     * Status of cancellation (204 if cancelled successfully or error status code)
     *
     * @var ?int $status
     */
    #[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $status = null;

    /**
     * An object that complies with RFC 9457 containing information about a request error
     *
     * @var ?ErrorResponse $error
     */
    #[\JMS\Serializer\Annotation\SerializedName('error')]
    #[\JMS\Serializer\Annotation\Type('\Gsmservice\Gateway\Models\Components\ErrorResponse|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?ErrorResponse $error = null;

    /**
     * @param  ?int  $id
     * @param  ?int  $status
     * @param  ?ErrorResponse  $error
     */
    public function __construct(?int $id = null, ?int $status = null, ?ErrorResponse $error = null)
    {
        $this->id = $id;
        $this->status = $status;
        $this->error = $error;
    }
}