<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gsmservice\Gateway\Models\Components;


/** IncomingMessage - An object with the properties of the received message */
class IncomingMessage
{
    /**
     * Unique identifier of incoming message
     *
     * @var ?int $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $id = null;

    /**
     * Login of the account (sub-account) on which the message was received
     *
     * @var ?string $login
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('login')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $login = null;

    /**
     * Recipient number (or service name)
     *
     * @var ?string $recipient
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recipient')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $recipient = null;

    /**
     * Message sender number (or alphanumeric name)
     *
     * @var ?string $sender
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sender')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sender = null;

    /**
     * Date and time of message receipt in ISO 8601 format
     *
     * @var ?\DateTime $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $date = null;

    /**
     * Received message content
     *
     * @var ?string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $message = null;

    /**
     * Sender name (matched with phonebook)
     *
     * @var ?string $phonebookSenderName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phonebook_sender_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phonebookSenderName = null;

    /**
     * Dedicated Mobile Originated service number (if the message was received on this number)
     *
     * @var ?string $dedicatedNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dedicated_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $dedicatedNumber = null;

    /**
     * Dedicated Mobile Originated service prefix (if the message was received on this number with such prefix)
     *
     * @var ?string $dedicatedPrefix
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dedicated_prefix')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $dedicatedPrefix = null;

    /**
     * @param  ?int  $id
     * @param  ?string  $login
     * @param  ?string  $recipient
     * @param  ?string  $sender
     * @param  ?\DateTime  $date
     * @param  ?string  $message
     * @param  ?string  $phonebookSenderName
     * @param  ?string  $dedicatedNumber
     * @param  ?string  $dedicatedPrefix
     * @phpstan-pure
     */
    public function __construct(?int $id = null, ?string $login = null, ?string $recipient = null, ?string $sender = null, ?\DateTime $date = null, ?string $message = null, ?string $phonebookSenderName = null, ?string $dedicatedNumber = null, ?string $dedicatedPrefix = null)
    {
        $this->id = $id;
        $this->login = $login;
        $this->recipient = $recipient;
        $this->sender = $sender;
        $this->date = $date;
        $this->message = $message;
        $this->phonebookSenderName = $phonebookSenderName;
        $this->dedicatedNumber = $dedicatedNumber;
        $this->dedicatedPrefix = $dedicatedPrefix;
    }
}