<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gsmservice\Gateway\Models\Components;


/**
 * Message type according to the table:
 *
 *     
 * |type|Description|
 * |----|-----------|
 * |  1 | SMS PRO   |
 * |  3 | SMS ECO   |
 * |  4 | SMS 2WAY  |
 * | 10 | MMS       |
 */
enum MessageType: int
{
    case SmsPro = 1;
    case SmsEco = 3;
    case SmsTwoWay = 4;
    case Mms = 10;
}
