<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gsmservice\Gateway\Models\Components;


/** MmsMessage - An object with a new MMS message properties */
class MmsMessage
{
    /**
     * The recipient number or multiple recipients numbers of single message. To set one recipient, simply pass here a `string` with his phone number. To set multiple recipients, pass here a simple `array` of `string`. Optionally you can also set custom id (user identifier) for each message - pass `PhoneNumberWithCid` object (in case of single recipient) or `Array` of `PhoneNumberWithCid` (in case of multiple recipients).
     *
     * @var string|array<string>|PhoneNumberWithCid|array<PhoneNumberWithCid> $recipients
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recipients')]
    #[\Speakeasy\Serializer\Annotation\Type('string|array<string>|\Gsmservice\Gateway\Models\Components\PhoneNumberWithCid|array<\Gsmservice\Gateway\Models\Components\PhoneNumberWithCid>')]
    public string|array|PhoneNumberWithCid $recipients;

    /**
     * Attachments for the message. You can pass here images, audio and video files bodies. To set one attachment please pass a `string` with attachment body encoded by `base64_encode()` function. To set multiple attachments - pass an `array` of `strings` with attachment bodies encoded by `base64_encode()` function. Max 3 attachments per message.
     *
     * @var string|array<string>|null $attachments
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attachments')]
    #[\Speakeasy\Serializer\Annotation\Type('string|array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|array|null $attachments = null;

    /**
     * MMS message subject
     *
     * @var ?string $subject
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subject')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $subject = null;

    /**
     * MMS message content
     *
     * @var ?string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $message = null;

    /**
     * Scheduled future date and time of sending the message (in ISO 8601 format). If missing or null - message will be sent immediately
     *
     * @var ?\DateTime $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $date = null;

    /**
     * @param  string|array<string>|PhoneNumberWithCid|array<PhoneNumberWithCid>  $recipients
     * @param  string|array<string>|null  $attachments
     * @param  ?string  $subject
     * @param  ?string  $message
     * @param  ?\DateTime  $date
     * @phpstan-pure
     */
    public function __construct(string|array|PhoneNumberWithCid $recipients, string|array|null $attachments = null, ?string $subject = null, ?string $message = null, ?\DateTime $date = null)
    {
        $this->recipients = $recipients;
        $this->attachments = $attachments;
        $this->subject = $subject;
        $this->message = $message;
        $this->date = $date;
    }
}