<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gsmservice\Gateway\Models\Components;


/** PingResponse - 'Ping' response object */
class PingResponse
{
    /**
     * API service status: OK - API available, ERR - API unavailable
     *
     * @var ?string $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $status = null;

    /**
     * Current API Version
     *
     * @var ?string $version
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('version')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $version = null;

    /**
     * Was the connection established with the test system (SANDBOX)?
     *
     * @var ?bool $sandbox
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sandbox')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $sandbox = null;

    /**
     * @param  ?string  $status
     * @param  ?string  $version
     * @param  ?bool  $sandbox
     * @phpstan-pure
     */
    public function __construct(?string $status = null, ?string $version = null, ?bool $sandbox = null)
    {
        $this->status = $status;
        $this->version = $version;
        $this->sandbox = $sandbox;
    }
}