<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gsmservice\Gateway\Models\Components;


/** Price - An object with the properties and price of a single message */
class Price
{
    /**
     * Message type (SmsType::SmsPro -> SMS PRO, SmsType::SmsEco -> SMS ECO, SmsType::SmsTwoWay ->SMS 2WAY, SmsType::Mms -> MMS)
     *
     * @var ?MessageType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gsmservice\Gateway\Models\Components\MessageType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?MessageType $type = null;

    /**
     * A telephone number in international format (with a plus sign and the country code at the beginning, e.g. +48 for Poland)
     *
     * @var ?string $recipient
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recipient')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $recipient = null;

    /**
     * Did the message contain special characters, e.g. Polish diacritics?
     *
     * @var ?bool $unicode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('unicode')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $unicode = null;

    /**
     * Was the message sent with class 0 (FLASH)?
     *
     * @var ?bool $flash
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('flash')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $flash = null;

    /**
     * The price of message (in PLN)
     *
     * @var ?float $price
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $price = null;

    /**
     * Information about a possible error
     *
     * @var ?string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $error = null;

    /**
     * Custom message ID assigned by the User
     *
     * @var ?string $cid
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cid')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $cid = null;

    /**
     * Message sender name
     *
     * @var ?string $sender
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sender')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sender = null;

    /**
     * The count of parts that message consists of
     *
     * @var ?int $parts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parts')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $parts = null;

    /**
     * @param  ?MessageType  $type
     * @param  ?string  $recipient
     * @param  ?bool  $unicode
     * @param  ?bool  $flash
     * @param  ?float  $price
     * @param  ?string  $error
     * @param  ?string  $cid
     * @param  ?string  $sender
     * @param  ?int  $parts
     * @phpstan-pure
     */
    public function __construct(?MessageType $type = null, ?string $recipient = null, ?bool $unicode = null, ?bool $flash = null, ?float $price = null, ?string $error = null, ?string $cid = null, ?string $sender = null, ?int $parts = null)
    {
        $this->type = $type;
        $this->recipient = $recipient;
        $this->unicode = $unicode;
        $this->flash = $flash;
        $this->price = $price;
        $this->error = $error;
        $this->cid = $cid;
        $this->sender = $sender;
        $this->parts = $parts;
    }
}